### ISSUE TITLE
Remove util.extract_tower_json shortcut

### ISSUE THREAD

**Issue by thijstriemstra** [collab-project/django-require-i18n#1]
Leads to errors like this:

```
Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/private/var/folders/jc/c_vnhmp15sn_pbbssg69y95w0000gn/T/pip-build-BvgDxI/django-require-i18n/setup.py", line 5, in <module>

        from require_i18n import version

      File "require_i18n/__init__.py", line 4, in <module>

        from .util import extract_tower_json

      File "require_i18n/util.py", line 7, in <module>

        from tower import tweak_message

    ImportError: No module named tower
```

**Comment by thijstriemstra** [comment]
Released in 1.2.0.
